Removed static mbedtls memory allocation from all programs
Fraunhofer-AISEC/lazarus pull request #5
Opened 2022-01-21 13:59 UTC by Lennerados

We needed this before due to out of memory problems caused by mbedtls. This could be solved by increasing the heap size of the projects in the linker script. I also unified the heap and stack size for all programs.

2022-01-22 08:33 UTC, oxisto commented on lz_common/mbedtls/port/ksdk/ksdk_mbedtls_config.h
> + * (In-)Security of 64-bit Block Ciphers" by Karthikeyan Bhargavan and Ga�tan
Looks like some UTF problem

2022-01-23 10:43 UTC, Lennerados commented on lz_common/mbedtls/port/ksdk/ksdk_mbedtls_config.h
> + * (In-)Security of 64-bit Block Ciphers" by Karthikeyan Bhargavan and Ga�tan
Should be fixed now. Thanks

2022-01-26 10:26 UTC, smo4201 requested changes
Please squash the UTF-8 fix commit into the first commit and then force push to your repository branch to update the pull request for a clean history

2022-01-26 20:06 UTC, smo4201 approved these changes

2022-01-26 20:07 UTC, merged